version: '3.8'

services:
  # 🚀 Main FastAPI Application
  mefapex-app:
    build:
      context: .
      dockerfile: Dockerfile.fixed
    container_name: mefapex-chatbox
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=production
      - DEBUG=false
      - DATABASE_URL=sqlite:///./data/mefapex.db
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - USE_OPENAI=false
      - USE_HUGGINGFACE=true
      - CORS_ORIGINS=http://localhost:3000,http://localhost:8000
    volumes:
      - ./data:/app/data
      - ./models_cache:/app/models_cache
      - ./logs:/app/logs
    depends_on:
      - qdrant
      - redis
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - mefapex-network

  # 🗄️ Qdrant Vector Database
  qdrant:
    image: qdrant/qdrant:v1.7.4
    container_name: mefapex-qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__SERVICE__GRPC_PORT=6334
    volumes:
      - qdrant_data:/qdrant/storage
    restart: unless-stopped
    networks:
      - mefapex-network

  # 🗂️ Redis Cache
  redis:
    image: redis:7.2-alpine
    container_name: mefapex-redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - mefapex-network

  # 📊 Nginx Reverse Proxy (Optional)
  nginx:
    image: nginx:alpine
    container_name: mefapex-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - mefapex-app
    restart: unless-stopped
    networks:
      - mefapex-network

  # 📈 Monitoring Dashboard (Optional)
  monitoring:
    image: prom/prometheus:latest
    container_name: mefapex-monitoring
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    restart: unless-stopped
    networks:
      - mefapex-network

volumes:
  qdrant_data:
    driver: local
  redis_data:
    driver: local
  prometheus_data:
    driver: local

networks:
  mefapex-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
