version: '3.8'

services:
  # 🚀 Main FastAPI Application (Simplified)
  mefapex-app:
    build:
      context: .
      dockerfile: Dockerfile.simple
    container_name: mefapex-chatbox
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=production
      - DEBUG=false
    volumes:
      - ./data:/app/data
      - ./models_cache:/app/models_cache
      - ./logs:/app/logs
      - ./static:/app/static
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - mefapex-network

  # 📊 Nginx Reverse Proxy (Optional)
  nginx:
    image: nginx:alpine
    container_name: mefapex-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - ./static:/var/www/html/static:ro
    depends_on:
      - mefapex-app
    restart: unless-stopped
    networks:
      - mefapex-network

networks:
  mefapex-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
